name: default_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - torchvision
  - torchtext
  - optuna
  - tqdm
  - plotly
  - jupyter
  - jupyterlab
  - nodejs
  - pip:
    - torch
    - torchsde
    - torchaudio
    - pytorch-transformers
    - h5py
    - matplotlib
    - rich
    - wfdb